# Workflow name
name: My First Workflow

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

  # Automatic trigger on pull request events targeting the master/main branches
  pull_request:
    branches:
      - main
      - master

  # Automatic trigger on pull request events targeting the master/main branches
  push:
    branches:
      - main
      - master

  # Scheduled trigger at 5:00 AM UTC, Monday through Friday
  schedule:
    - cron: '0 5 * * 1-5'

# Jobs defined in the workflow
jobs:
  build:

    # The operating system for the runner
    runs-on: ubuntu-latest

    # Steps in the job
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: latest

    - name: Print a message
      run: echo "Hello, world!"